const map = L.map('map').setView([36.2, 138.2], 5);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; OpenStreetMap contributors' }).addTo(map);
delete L.Icon.Default.prototype._getIconUrl;
L.Icon.Default.mergeOptions({ iconRetinaUrl: 'https://cdn.jsdelivr.net/npm/leaflet@1.9.4/dist/images/marker-icon-2x.png', iconUrl: 'https://cdn.jsdelivr.net/npm/leaflet@1.9.4/dist/images/marker-icon.png', shadowUrl: 'https://cdn.jsdelivr.net/npm/leaflet@1.9.4/dist/images/marker-shadow.png' });
const statusEl = document.getElementById('status');
const topicListEl = document.getElementById('topicList');
const markers = [];
function esc(v) { return String(v ?? '').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;'); }
function popup(p) { const link = esc(p.link); return `<strong>${esc(p.title)}</strong><br><span>${esc(p.representative_place)}</span><br><small>${esc(p.place_type)}</small><br><p>${esc(p.place_reason)}</p>${link ? `<a href="${link}" target="_blank" rel="noopener noreferrer">${esc(p.source) || 'source'}</a>` : ''}`; }
function addList(feature, marker) { const p = feature.properties || {}; const item = document.createElement('div'); item.className = 'topic-item'; item.innerHTML = `<div class="topic-title">${esc(p.title)}</div><div class="topic-meta">${esc(p.representative_place)} / ${esc(p.place_type)}</div>`; item.addEventListener('click', () => { marker.openPopup(); map.setView(marker.getLatLng(), Math.max(map.getZoom(), 12)); }); topicListEl.appendChild(item); }
fetch('./latest.geojson', { cache: 'no-store' }).then(r => { if (!r.ok) throw new Error(`HTTP ${r.status}`); return r.json(); }).then(geojson => { const features = geojson.features || []; features.forEach(feature => { const c = feature.geometry && feature.geometry.coordinates; if (!c || c.length < 2) return; const marker = L.marker([c[1], c[0]]).addTo(map); marker.bindPopup(popup(feature.properties || {})); markers.push(marker); addList(feature, marker); }); if (markers.length) { map.fitBounds(L.featureGroup(markers).getBounds().pad(0.25)); } const createdAt = geojson.properties && geojson.properties.created_at; statusEl.textContent = `${markers.length}件のニュース地点` + (createdAt ? ` / ${createdAt}` : ''); }).catch(e => { console.error(e); statusEl.textContent = 'latest.geojson の読み込みに失敗しました。'; });
